version: '3.4'

services:
  reverse-proxy:
    image: 'nginx:1.25.2'
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./frontend/dist:/data/static:ro